java_test(
    name = "FiveTest",
    srcs = ["FiveTest.java"],
    deps = [
        "//third_party/java/junit",
        "//third_party/java/org/junit/jupiter:junit_jupiter_api",
        "//third_party/java/org/junit/jupiter:junit_jupiter_engine",
        "//third_party/java/org/junit/platform:junit_platform_runner",
    ],
)

java_test(
    name = "FourTest",
    srcs = ["FourTest.java"],
    deps = [
        "//third_party/java/junit",
    ],
)
